notify-event-ts:
  build: .
#  ports:
#    - '3000:3000'
  volumes:
    - .:/home/app/net
    - /home/app/net/node_modules
  environment:
    - TS_SERVERADMIN=serveradmin
    - TS_PORT=10011
    - TS_SA_PASSWORD=
